authors:
  HoanTran:
    name: HoanTran
    description: Người thích tìm tòi và ứng dụng AI
    avatar: https://github.com/hoantran-lab.png
  tranvanhoan:
    name: HoanTran
    description: Người thích tìm tòi và ứng dụng AI
    avatar: https://github.com/hoantran-lab.png
